version: '3.8'

services:
  db:
    image: quay.io/sclorg/postgresql-15-c9s
    environment:
      POSTGRESQL_USER: user
      POSTGRESQL_PASSWORD: pass
      POSTGRESQL_DATABASE: mydb
    volumes:
      - event_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: quay.io/lib/adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  event_data: