version: '3.8'

services:
  db:
    image: docker.io/library/postgres:13.22-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - event_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: docker.io/library/adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  event_data: